/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "timer_clock.h"
#include "LED_UpdateTimer.h"
#include "LED_UpdateISR.h"
#include "Red_LED.h"
#include "Red_LED_aliases.h"
#include "Green_LED.h"
#include "Green_LED_aliases.h"
#include "Amber_LED.h"
#include "Amber_LED_aliases.h"
#include "Left_Red_LED.h"
#include "Left_Red_LED_aliases.h"
#include "Left_Green_LED.h"
#include "Left_Green_LED_aliases.h"
#include "Left_Amber_LED.h"
#include "Left_Amber_LED_aliases.h"
#include "Right_Red_LED.h"
#include "Right_Red_LED_aliases.h"
#include "Right_Green_LED.h"
#include "Right_Green_LED_aliases.h"
#include "Right_Amber_LED.h"
#include "Right_Amber_LED_aliases.h"
#include "Front_Red_LED.h"
#include "Front_Red_LED_aliases.h"
#include "Front_Green_LED.h"
#include "Front_Green_LED_aliases.h"
#include "Front_Amber_LED.h"
#include "Front_Amber_LED_aliases.h"
#include "LCD.h"
#include "AfterHours.h"
#include "AfterHours_aliases.h"
#include "timer_clock_1.h"
#include "SW_ISR1.h"
#include "Setting_mode.h"
#include "Setting_mode_aliases.h"
#include "SW_ISR2.h"
#include "timer_clock_2.h"
#include "ADC.h"
#include "POT.h"
#include "POT_aliases.h"
#include "UART.h"
#include "EEPROM.h"
#include "LCD_LCDPort.h"
#include "LCD_LCDPort_aliases.h"
#include "ADC_AMux.h"
#include "ADC_Ext_CP_Clk.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "UART_IntClock.h"
#include "cy_em_eeprom.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "PSoC3_8051.h"

/*[]*/

